`timescale 1ns / 1ps
//All rights reserved
// Author: Jonas Bertels on behalf of COSIC, KU Leuven
// MAY NOT BE REPRODUCED

`include "ntt_params.v"



// BEGIN APPLICATION-SPECIFIC PARAMETERS HERE (In this case a hodgepodge of Kyber and FINAL params, 
// use your own for your NTT-specific application)
`define ONE_CYCLE_ITERATION 1
`define TWO_CYCLE_ITERATION 2
`define EIGHT_CYCLE_ITERATION 8
`define THIRTY_FOUR_CYCLE_ITERATION 34
`define FULL_CYCLE_ITERATION 610
`define ITERATIONS `TWO_CYCLE_ITERATION
`define ITERATION_DEPTH $clog2(`ITERATIONS)

`define BSK_SIZE        (`COEF_PER_CLOCK_CYCLE*`L*`NTT_DIV_BY_RING*`ITERATIONS)
`define COUNTER_SIZE       ($clog2(`NTT_DIV_BY_RING*`ITERATIONS*`BATCH_SIZE))
`define CMUX_COUNTER_SIZE ($clog2(`NTT_DIV_BY_RING*`FULL_CYCLE_ITERATION*`BATCH_SIZE))
`define BSK_COUNTER_SIZE       ($clog2(`NTT_DIV_BY_RING*`ITERATIONS*`L))

`define BATCH_DEPTH     5
`define BATCH_SIZE      (1 << `BATCH_DEPTH)


`define STREAM_SIZE 32
`define STREAM_ADDR_WIDTH  ($clog2(`STREAM_SIZE))
`define STREAM_COUNTER_SIZE (`COEF_PER_CLOCK_CYCLE*`COEF_PER_CLOCK_CYCLE*`MODULUS_WIDTH>>`STREAM_ADDR_WIDTH)
`define COUNTER_WIDTH (($clog2(`STREAM_COUNTER_SIZE))+1)
`define ADDR_WIDTH ($clog2(`MODULUS_WIDTH))
`define HBM_WIDTH 32
`define STAGE_REDUCTION 3

`define BRAM_SIZE (2*`COEF_PER_CLOCK_CYCLE)
`define HBM_ELEMENT_SIZE 16
`define HBM_ELEMENT_DEPTH 4





// ------------------------------------------------
// FINAL parameters
`define L 7 
`define L_WIDTH ($clog2(`L))
`define L_CEIL 1<<`L_WIDTH
`define B_BSK_WIDTH 3 //$ceil(`MODULUS_WIDTH/`L)


//LATENCY parameters, because this reduces useless control logic and design complexity

`define NTT_4096_LATENCY 321
`define NTT_1024_LATENCY (2*`MATRIX_TRANSPOSE_LATENCY+(`JEWEL_REGISTERS*`LOG_N+2*`TAIL_REDUCTION)+`MULTIPLIER_LATENCY+`REDUCTION_LATENCY)
`define MAC_LATENCY (14+`MULTIPLIER_LATENCY+1+`REDUCTION_LATENCY+2+`REDUCTION_LATENCY)

`define EXTERNAL_PRODUCT_LATENCY (`MATRIX_TRANSPOSE_LATENCY+`L+1+`FORWARD_NTT_1024_LATENCY+`MAC_LATENCY+`NTT_1024_LATENCY)
`define CMUX_LATENCY (2+`STAGE_SIZE+1+`NTT_DIV_BY_RING+3+2)

