`timescale 1ns / 1ps
//All rights reserved
// Author: Jonas Bertels on behalf of COSIC, KU Leuven
// MAY NOT BE REPRODUCED

`include "ntt_params.v"



// BEGIN APPLICATION-SPECIFIC PARAMETERS HERE (In this case a hodgepodge of Kyber and FINAL params, 
// use your own for your NTT-specific application)
`define ONE_CYCLE_ITERATION 1
`define TWO_CYCLE_ITERATION 2
`define EIGHT_CYCLE_ITERATION 8
`define THIRTY_FOUR_CYCLE_ITERATION 34
`define FULL_CYCLE_ITERATION 610
`define ITERATIONS `TWO_CYCLE_ITERATION
`define ITERATION_DEPTH $clog2(`ITERATIONS)

`define BSK_SIZE        (`COEF_PER_CLOCK_CYCLE*`L*`NTT_DIV_BY_RING*`ITERATIONS)
`define COUNTER_SIZE       ($clog2(`NTT_DIV_BY_RING*`ITERATIONS*`BATCH_SIZE))
`define CMUX_COUNTER_SIZE ($clog2(`NTT_DIV_BY_RING*`FULL_CYCLE_ITERATION*`BATCH_SIZE))
`define BSK_COUNTER_SIZE       ($clog2(`NTT_DIV_BY_RING*`ITERATIONS*`L))

`define BATCH_DEPTH     5
`define BATCH_SIZE      (1 << `BATCH_DEPTH)


`define STREAM_SIZE 32
`define STREAM_ADDR_WIDTH  ($clog2(`STREAM_SIZE))
`define STREAM_COUNTER_SIZE (`COEF_PER_CLOCK_CYCLE*`COEF_PER_CLOCK_CYCLE*`MODULUS_WIDTH>>`STREAM_ADDR_WIDTH)
`define COUNTER_WIDTH (($clog2(`STREAM_COUNTER_SIZE))+1)
`define ADDR_WIDTH ($clog2(`MODULUS_WIDTH))
`define HBM_WIDTH 32
`define STAGE_REDUCTION 3

`define BRAM_SIZE (2*`COEF_PER_CLOCK_CYCLE)
`define HBM_ELEMENT_SIZE 16
`define HBM_ELEMENT_DEPTH 4





// ------------------------------------------------
// FINAL parameters
`define L 7 
`define L_WIDTH ($clog2(`L))
`define L_CEIL 1<<`L_WIDTH
`define B_BSK_WIDTH 3 //$ceil(`MODULUS_WIDTH/`L)


//LATENCY parameters, because this reduces useless control logic and design complexity

`define NTT_4096_LATENCY 321
`define NTT_1024_LATENCY (2*`MATRIX_TRANSPOSE_LATENCY+(`JEWEL_REGISTERS*`LOG_N+2*`TAIL_REDUCTION)+`MULTIPLIER_LATENCY+`REDUCTION_LATENCY)
`define MAC_LATENCY (14+`MULTIPLIER_LATENCY+1+`REDUCTION_LATENCY+2+`REDUCTION_LATENCY)

`define EXTERNAL_PRODUCT_LATENCY (`MATRIX_TRANSPOSE_LATENCY+`L+1+`FORWARD_NTT_1024_LATENCY+`MAC_LATENCY+`NTT_1024_LATENCY)
`define CMUX_LATENCY (2+`STAGE_SIZE+1+`NTT_DIV_BY_RING+3+2)


//------------------------------------------------
// Kyber-768 parameters

//KECCAK PARAMS
`define ROUNDS_OF_KECCAK 24
`define LOG_ROUNDS_OF_KECCAK ($clog2(`ROUNDS_OF_KECCAK))
`define LATENCY_BETWEEN_BURSTS `ROUNDS_OF_KECCAK
`define BURST_SIZE (`ROUNDS_OF_KECCAK>>(`LOG_N-`LOG_COEF_PER_CC))
`define BURST_SIZE_DIV_BY_3 (`BURST_SIZE/3)
`define KECCAK_WIDTH 1600

// SHA-cluster params
`define INPUT_WIDTH_CLUSTER_MESSAGE 256
`define INPUT_WIDTH_CLUSTER_PK (9472)
`define SHAKE_256_INPUT (`SHA_256_OUTPUT+8)
`define SHAKE_128_INPUT (`SHA_256_OUTPUT+16)
`define BURST_LEN_INPUT (BURST_SIZE)

`define OUTPUT_WIDTH_CLUSTER_SHAKE_256 1024
`define OUTPUT_WIDTH_ONE_BURST_SHAKE_128 1344
`define OUTPUT_WIDTH_CLUSTER_SHAKE_128 (5*`OUTPUT_WIDTH_ONE_BURST_SHAKE_128)
`define OUTPUT_WIDTH_BURST_256 (`COEF_PER_CLOCK_CYCLE*4)
`define HARDCODE_MULT 1259 // int(2**(22)/3329)
`define SAMPLE_INPUT_WIDTH 4

`define K_WIDTH ((`SHA_512_OUTPUT/2)>>(`LOG_N-`LOG_COEF_PER_CC))

//SHA-3-256
//`define SHA_3_256_INPUT_WIDTH INPUT_WIDTH_CLUSTER_PK
`define SHA_128_DATA_RATE (`KECCAK_WIDTH-256)
`define SHA_256_DATA_RATE 1088
`define SHA_512_DATA_RATE 576

`define SHAKE_COUNTER_SIZE 8 
`define SHA_256_OUTPUT 256
`define SHA_512_OUTPUT 512

`define SAMPLE_NTT_LATENCY `LOG_N*`LOG_N
// TOTAL PARAMS
`define OUTPUT_WIDTH 1088
`define CIPHERTEXT_WIDTH ((`D_U*`COEF_PER_CLOCK_CYCLE)+(`D_V*`COEF_PER_CLOCK_CYCLE))
`define TOTAL_LATENCY_ENCRYPTION (`FORWARD_NTT_1024_LATENCY+5*`ROUNDS_OF_KECCAK+`MULTIPLIER_LATENCY+`REDUCTION_LATENCY+`SAMPLE_NTT_LATENCY)
`define MESSAGE_LATENCY (`ROUNDS_OF_KECCAK+`CAPTURE_R_LATENCY+2*`FORWARD_NTT_1024_LATENCY+`SAMPLE_POLY_CBD_LATENCY+`BURST_LATENCY+(`ACCUMULATOR_LATENCY+`COEF_MULT_2))
`define SAMPLE_POLY_CBD_LATENCY 1
`define SMALL_K 3
`define ACCUMULATOR_LATENCY ((`ROUNDS_OF_KECCAK-`ONE_THIRD_KECCAK)+2+`REDUCTION_LATENCY)
`define COEF_MULT_2 (`MULTIPLIER_LATENCY+`REDUCTION_LATENCY+`MULTIPLIER_LATENCY+1+`REDUCTION_LATENCY)
`define E2_LATENCY (2*`FORWARD_NTT_1024_LATENCY+`COEF_MULT_2)
`define BURST_LATENCY 2
`define COMPRESS_LATENCY 5
`define ADDITION_LATENCY 1
`define CAPTURE_R_LATENCY 1

`define D_V 4
`define D_U 10

// TEST PARAMETERS
`define TEST_CLOCK_CYCLES `BURST_SIZE
`define TEST_CLOCK_CYCLES_ONE_THIRD `BURST_SIZE_DIV_BY_3

`define ONE_THIRD_KECCAK (`ROUNDS_OF_KECCAK/3)